name: Commit Check Workflow

on: [push, pull_request]

jobs:
  setup:
      runs-on: ubuntu-latest
      outputs:
        node-version: ${{ steps.node-version.outputs.node-version }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup Node.js
          id: node-version
          uses: actions/setup-node@v3
          with:
            node-version: "20"
        
        - name: Cache Node.js dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Install dependencies
          run: npm ci 

  lint:
    runs-on: ubuntu-latest
    needs: setup 
    steps:
      - name: Run ESLint
        run: npm run lint

  typescript:
    runs-on: ubuntu-latest
    needs: setup 
    steps:
      - name: TypeScript Type Check
        run: npx tsc --noEmit

  build:
    runs-on: ubuntu-latest
    needs: setup 
    steps:
        - name: Build Project
          run: npm run build

  audit:
    runs-on: ubuntu-latest
    needs: setup 
    steps:
      - name: Audit Dependencies
        run: npm audit --production
