name: Commit Check Workflow

on: [push, pull_request]

jobs:
  setup:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: "20"
          - run: npm ci

  lint:
    needs: setup 
    runs-on: ubuntu-latest
    steps:
      - name: Run ESLint
        run: npm run lint

  typescript:
    needs: setup 
    runs-on: ubuntu-latest
    steps:
      - name: TypeScript Type Check
        run: npx tsc --noEmit

  build:
    needs: setup 
    runs-on: ubuntu-latest
    steps:
        - name: Build Project
          run: npm run build

  audit:
    needs: setup 
    runs-on: ubuntu-latest
    steps:
      - name: Audit Dependencies
        run: npm audit --production
